; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-n16r8]
platform = espressif32 @ ^6.0.1
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.partitions = partitions.csv
lib_deps = 
	bblanchon/ArduinoJson@^7.2.1
	h2zero/NimBLE-Arduino@^1.4.3
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit MAX1704X@^1.0.3
	mikalhart/TinyGPSPlus@^1.1.0
	adafruit/Adafruit LIS2MDL@^2.1.8
	adafruit/Adafruit AHRS@^2.3.3
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF32_ENABLE_SPIFFS
	
	-ffast-math
monitor_speed = 115200
