// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#ifndef _DRAARL_ESP32_V1_UI_H
#define _DRAARL_ESP32_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_StartUP.h"
#include "ui_main.h"
#include "ui_SettingPAGE.h"
#include "ui_InfoPage.h"
#include "ui_RFPAGE.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_bad_png);    // assets/wifi_bad.png
LV_IMG_DECLARE(
    ui_img_bluetooth_disabled_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/bluetooth_disabled_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_browser_updated_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/browser_updated_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/settings_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_cloud_sync_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/cloud_sync_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_cloud_alert_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/cloud_alert_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_bluetooth_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/bluetooth_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_bluetooth_connected_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/bluetooth_connected_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_cloud_done_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/cloud_done_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets/wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets/wifi_2.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets/wifi_3.png
LV_IMG_DECLARE(ui_img_wifi_4_png);    // assets/wifi_4.png
LV_IMG_DECLARE(ui_img_wifi_off_png);    // assets/wifi_off.png

// FONTS
LV_FONT_DECLARE(ui_font_system);
LV_FONT_DECLARE(ui_font_system20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
