// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#include "ui.h"

lv_obj_t * ui_InfoPage = NULL;
lv_obj_t * ui_InfoP1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Mac = NULL;
lv_obj_t * ui_Mac1 = NULL;
lv_obj_t * ui_ip2 = NULL;
lv_obj_t * ui_Callsign = NULL;
lv_obj_t * ui_username = NULL;
lv_obj_t * ui_header4 = NULL;
lv_obj_t * ui_logo4 = NULL;
lv_obj_t * ui_title3 = NULL;
lv_obj_t * ui_wifistat3 = NULL;
lv_obj_t * ui_bluestat3 = NULL;
lv_obj_t * ui_hasNewUpdate3 = NULL;
// event funtions

// build funtions

void ui_InfoPage_screen_init(void)
{
    ui_InfoPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InfoPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InfoP1 = lv_obj_create(ui_InfoPage);
    lv_obj_set_width(ui_InfoP1, 310);
    lv_obj_set_height(ui_InfoP1, 200);
    lv_obj_set_x(ui_InfoP1, 0);
    lv_obj_set_y(ui_InfoP1, 15);
    lv_obj_set_align(ui_InfoP1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InfoP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_InfoP1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -99);
    lv_obj_set_y(ui_Label5, 2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Mac地址:\n\n服务器地址:\n\nWIFI IP:\n\n呼号:\n\n账号:");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_system, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mac = lv_label_create(ui_InfoP1);
    lv_obj_set_width(ui_Mac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mac, 73);
    lv_obj_set_y(ui_Mac, -70);
    lv_obj_set_align(ui_Mac, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mac, "11:22:33:44");
    lv_obj_set_style_text_color(ui_Mac, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mac, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mac1 = lv_label_create(ui_InfoP1);
    lv_obj_set_width(ui_Mac1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mac1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mac1, 47);
    lv_obj_set_y(ui_Mac1, -35);
    lv_obj_set_align(ui_Mac1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mac1, "ptt.4l2.cn:60050");
    lv_obj_set_style_text_color(ui_Mac1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mac1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mac1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ip2 = lv_label_create(ui_InfoP1);
    lv_obj_set_width(ui_ip2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ip2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ip2, 64);
    lv_obj_set_y(ui_ip2, 0);
    lv_obj_set_align(ui_ip2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ip2, "192.168.1.100");
    lv_obj_set_style_text_color(ui_ip2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ip2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ip2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Callsign = lv_label_create(ui_InfoP1);
    lv_obj_set_width(ui_Callsign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Callsign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Callsign, 78);
    lv_obj_set_y(ui_Callsign, 38);
    lv_obj_set_align(ui_Callsign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Callsign, "BH5UVN");
    lv_obj_set_style_text_color(ui_Callsign, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Callsign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Callsign, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_username = lv_label_create(ui_InfoP1);
    lv_obj_set_width(ui_username, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_username, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_username, 88);
    lv_obj_set_y(ui_username, 74);
    lv_obj_set_align(ui_username, LV_ALIGN_CENTER);
    lv_label_set_text(ui_username, "admin");
    lv_obj_set_style_text_color(ui_username, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_username, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_username, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header4 = lv_obj_create(ui_InfoPage);
    lv_obj_remove_style_all(ui_header4);
    lv_obj_set_width(ui_header4, 320);
    lv_obj_set_height(ui_header4, 30);
    lv_obj_set_x(ui_header4, 0);
    lv_obj_set_y(ui_header4, -105);
    lv_obj_set_align(ui_header4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_header4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_header4, lv_color_hex(0x22262D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo4 = lv_label_create(ui_header4);
    lv_obj_set_width(ui_logo4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo4, -110);
    lv_obj_set_y(ui_logo4, 0);
    lv_obj_set_align(ui_logo4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logo4, "DraARL-PTT");
    lv_obj_set_style_text_color(ui_logo4, lv_color_hex(0x00DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logo4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_logo4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title3 = lv_label_create(ui_header4);
    lv_obj_set_width(ui_title3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title3, "关于");
    lv_obj_set_style_text_font(ui_title3, &ui_font_system20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat3 = lv_img_create(ui_header4);
    lv_img_set_src(ui_wifistat3, &ui_img_wifi_bad_png);
    lv_obj_set_width(ui_wifistat3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifistat3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifistat3, 140);
    lv_obj_set_y(ui_wifistat3, 0);
    lv_obj_set_align(ui_wifistat3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifistat3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bluestat3 = lv_img_create(ui_header4);
    lv_img_set_src(ui_bluestat3, &ui_img_bluetooth_disabled_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_bluestat3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_bluestat3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_bluestat3, 110);
    lv_obj_set_y(ui_bluestat3, 0);
    lv_obj_set_align(ui_bluestat3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bluestat3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluestat3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hasNewUpdate3 = lv_img_create(ui_header4);
    lv_img_set_src(ui_hasNewUpdate3, &ui_img_browser_updated_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_hasNewUpdate3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_hasNewUpdate3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_hasNewUpdate3, 80);
    lv_obj_set_y(ui_hasNewUpdate3, 0);
    lv_obj_set_align(ui_hasNewUpdate3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hasNewUpdate3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hasNewUpdate3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_InfoPage_screen_destroy(void)
{
    if(ui_InfoPage) lv_obj_del(ui_InfoPage);

    // NULL screen variables
    ui_InfoPage = NULL;
    ui_InfoP1 = NULL;
    ui_Label5 = NULL;
    ui_Mac = NULL;
    ui_Mac1 = NULL;
    ui_ip2 = NULL;
    ui_Callsign = NULL;
    ui_username = NULL;
    ui_header4 = NULL;
    ui_logo4 = NULL;
    ui_title3 = NULL;
    ui_wifistat3 = NULL;
    ui_bluestat3 = NULL;
    ui_hasNewUpdate3 = NULL;

}
