// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#ifndef UI_INFOPAGE_H
#define UI_INFOPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InfoPage
extern void ui_InfoPage_screen_init(void);
extern void ui_InfoPage_screen_destroy(void);
extern lv_obj_t * ui_InfoPage;
extern lv_obj_t * ui_InfoP1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Mac;
extern lv_obj_t * ui_Mac1;
extern lv_obj_t * ui_ip2;
extern lv_obj_t * ui_Callsign;
extern lv_obj_t * ui_username;
extern lv_obj_t * ui_header4;
extern lv_obj_t * ui_logo4;
extern lv_obj_t * ui_title3;
extern lv_obj_t * ui_wifistat3;
extern lv_obj_t * ui_bluestat3;
extern lv_obj_t * ui_hasNewUpdate3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

