// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_mainContainer;
extern lv_obj_t * ui_infoPanel;
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_Freq;
extern lv_obj_t * ui_TXCTCSS;
extern lv_obj_t * ui_RXCTCSS;
extern lv_obj_t * ui_CTCSSinfo;
extern lv_obj_t * ui_SQLinfo;
extern lv_obj_t * ui_RXSQL;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_wifistat;
extern lv_obj_t * ui_bluestat;
extern lv_obj_t * ui_hasNewUpdate;
extern lv_obj_t * ui_toSetting;
extern lv_obj_t * ui_server;
extern lv_obj_t * ui_configsync;
extern lv_obj_t * ui_serverstat;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

