// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#include "ui.h"

lv_obj_t * ui_main = NULL;
lv_obj_t * ui_Freq = NULL;
lv_obj_t * ui_TXCTCSS = NULL;
lv_obj_t * ui_RXCTCSS = NULL;
lv_obj_t * ui_CTCSSinfo = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_logo = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_wifistat = NULL;
lv_obj_t * ui_bluestat = NULL;
lv_obj_t * ui_hasNewUpdate = NULL;
lv_obj_t * ui_toSetting = NULL;
lv_obj_t * ui_server = NULL;
lv_obj_t * ui_configsync = NULL;
lv_obj_t * ui_serverstat = NULL;
// event funtions

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Freq = lv_label_create(ui_main);
    lv_obj_set_width(ui_Freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Freq, 0);
    lv_obj_set_y(ui_Freq, -7);
    lv_obj_set_align(ui_Freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Freq, "438.5000");
    lv_obj_set_style_text_color(ui_Freq, lv_color_hex(0x009BB2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Freq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Freq, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TXCTCSS = lv_label_create(ui_main);
    lv_obj_set_width(ui_TXCTCSS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TXCTCSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TXCTCSS, -50);
    lv_obj_set_y(ui_TXCTCSS, 40);
    lv_obj_set_align(ui_TXCTCSS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TXCTCSS, "88.5");
    lv_obj_set_style_text_color(ui_TXCTCSS, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TXCTCSS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TXCTCSS, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RXCTCSS = lv_label_create(ui_main);
    lv_obj_set_width(ui_RXCTCSS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RXCTCSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RXCTCSS, 80);
    lv_obj_set_y(ui_RXCTCSS, 40);
    lv_obj_set_align(ui_RXCTCSS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RXCTCSS, "88.5");
    lv_obj_set_style_text_color(ui_RXCTCSS, lv_color_hex(0xDDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RXCTCSS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RXCTCSS, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CTCSSinfo = lv_label_create(ui_main);
    lv_obj_set_width(ui_CTCSSinfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CTCSSinfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CTCSSinfo, 4);
    lv_obj_set_y(ui_CTCSSinfo, 40);
    lv_obj_set_align(ui_CTCSSinfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CTCSSinfo, "TX:                        RX:                   ");
    lv_obj_set_style_text_color(ui_CTCSSinfo, lv_color_hex(0x70FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CTCSSinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CTCSSinfo, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_width(ui_header, 320);
    lv_obj_set_height(ui_header, 30);
    lv_obj_set_x(ui_header, 0);
    lv_obj_set_y(ui_header, -105);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x22262D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_label_create(ui_header);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, -110);
    lv_obj_set_y(ui_logo, 0);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logo, "DraARL-PTT");
    lv_obj_set_style_text_color(ui_logo, lv_color_hex(0x00DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_logo, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_header);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "12:00");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat = lv_img_create(ui_header);
    lv_img_set_src(ui_wifistat, &ui_img_wifi_bad_png);
    lv_obj_set_width(ui_wifistat, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifistat, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifistat, 140);
    lv_obj_set_y(ui_wifistat, 0);
    lv_obj_set_align(ui_wifistat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifistat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bluestat = lv_img_create(ui_header);
    lv_img_set_src(ui_bluestat, &ui_img_bluetooth_disabled_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_bluestat, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_bluestat, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_bluestat, 110);
    lv_obj_set_y(ui_bluestat, 0);
    lv_obj_set_align(ui_bluestat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bluestat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluestat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hasNewUpdate = lv_img_create(ui_header);
    lv_img_set_src(ui_hasNewUpdate, &ui_img_browser_updated_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_hasNewUpdate, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_hasNewUpdate, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_hasNewUpdate, 80);
    lv_obj_set_y(ui_hasNewUpdate, 0);
    lv_obj_set_align(ui_hasNewUpdate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hasNewUpdate, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hasNewUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_toSetting = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_toSetting, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png, NULL);
    lv_imgbtn_set_src(ui_toSetting, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png, NULL);
    lv_imgbtn_set_src(ui_toSetting, LV_IMGBTN_STATE_DISABLED, NULL,
                      &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png, NULL);
    lv_imgbtn_set_src(ui_toSetting, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL,
                      &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png, NULL);
    lv_imgbtn_set_src(ui_toSetting, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL,
                      &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png, NULL);
    lv_imgbtn_set_src(ui_toSetting, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL,
                      &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png, NULL);
    lv_obj_set_width(ui_toSetting, 24);
    lv_obj_set_height(ui_toSetting, 24);
    lv_obj_set_x(ui_toSetting, 139);
    lv_obj_set_y(ui_toSetting, 100);
    lv_obj_set_align(ui_toSetting, LV_ALIGN_CENTER);

    ui_server = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_server);
    lv_obj_set_width(ui_server, 30);
    lv_obj_set_height(ui_server, 50);
    lv_obj_set_x(ui_server, -140);
    lv_obj_set_y(ui_server, 90);
    lv_obj_set_align(ui_server, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_server, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configsync = lv_img_create(ui_server);
    lv_img_set_src(ui_configsync, &ui_img_cloud_sync_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_configsync, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_configsync, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_configsync, 0);
    lv_obj_set_y(ui_configsync, -15);
    lv_obj_set_align(ui_configsync, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configsync, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configsync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serverstat = lv_img_create(ui_server);
    lv_img_set_src(ui_serverstat, &ui_img_cloud_alert_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_serverstat, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_serverstat, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_serverstat, 0);
    lv_obj_set_y(ui_serverstat, 15);
    lv_obj_set_align(ui_serverstat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serverstat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_serverstat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    ui_main = NULL;
    ui_Freq = NULL;
    ui_TXCTCSS = NULL;
    ui_RXCTCSS = NULL;
    ui_CTCSSinfo = NULL;
    ui_header = NULL;
    ui_logo = NULL;
    ui_time = NULL;
    ui_wifistat = NULL;
    ui_bluestat = NULL;
    ui_hasNewUpdate = NULL;
    ui_toSetting = NULL;
    ui_server = NULL;
    ui_configsync = NULL;
    ui_serverstat = NULL;

}
