// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#ifndef UI_RFPAGE_H
#define UI_RFPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RFPAGE
extern void ui_RFPAGE_screen_init(void);
extern void ui_RFPAGE_screen_destroy(void);
extern lv_obj_t * ui_RFPAGE;
extern lv_obj_t * ui_PWP;
extern lv_obj_t * ui_PWL;
extern lv_obj_t * ui_PWS;
extern lv_obj_t * ui_PWN;
extern lv_obj_t * ui_LimitP;
extern lv_obj_t * ui_PWL1;
extern lv_obj_t * ui_rfguard;
extern lv_obj_t * ui_rfguardsingle;
extern lv_obj_t * ui_rfguardwindow;
extern lv_obj_t * ui_rfguardmaxtxinwindow;
extern lv_obj_t * ui_header2;
extern lv_obj_t * ui_logo2;
extern lv_obj_t * ui_title1;
extern lv_obj_t * ui_wifistat1;
extern lv_obj_t * ui_bluestat1;
extern lv_obj_t * ui_hasNewUpdate1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

