// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#include "ui.h"

lv_obj_t * ui_RFPAGE = NULL;
lv_obj_t * ui_BLEP1 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_BLES1 = NULL;
lv_obj_t * ui_BLEN1 = NULL;
lv_obj_t * ui_header2 = NULL;
lv_obj_t * ui_logo2 = NULL;
lv_obj_t * ui_title1 = NULL;
lv_obj_t * ui_wifistat1 = NULL;
lv_obj_t * ui_bluestat1 = NULL;
lv_obj_t * ui_hasNewUpdate1 = NULL;
// event funtions

// build funtions

void ui_RFPAGE_screen_init(void)
{
    ui_RFPAGE = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RFPAGE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BLEP1 = lv_obj_create(ui_RFPAGE);
    lv_obj_set_width(ui_BLEP1, 310);
    lv_obj_set_height(ui_BLEP1, 40);
    lv_obj_set_x(ui_BLEP1, 0);
    lv_obj_set_y(ui_BLEP1, -63);
    lv_obj_set_align(ui_BLEP1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BLEP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_BLEP1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -125);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "功率:");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_system, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLES1 = lv_switch_create(ui_BLEP1);
    lv_obj_set_width(ui_BLES1, 50);
    lv_obj_set_height(ui_BLES1, 25);
    lv_obj_set_x(ui_BLES1, 115);
    lv_obj_set_y(ui_BLES1, 0);
    lv_obj_set_align(ui_BLES1, LV_ALIGN_CENTER);

    ui_BLEN1 = lv_label_create(ui_BLEP1);
    lv_obj_set_width(ui_BLEN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLEN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLEN1, 73);
    lv_obj_set_y(ui_BLEN1, 0);
    lv_obj_set_align(ui_BLEN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLEN1, "低");
    lv_obj_set_style_text_font(ui_BLEN1, &ui_font_system, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header2 = lv_obj_create(ui_RFPAGE);
    lv_obj_remove_style_all(ui_header2);
    lv_obj_set_width(ui_header2, 320);
    lv_obj_set_height(ui_header2, 30);
    lv_obj_set_x(ui_header2, 0);
    lv_obj_set_y(ui_header2, -105);
    lv_obj_set_align(ui_header2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_header2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_header2, lv_color_hex(0x22262D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo2 = lv_label_create(ui_header2);
    lv_obj_set_width(ui_logo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo2, -110);
    lv_obj_set_y(ui_logo2, 0);
    lv_obj_set_align(ui_logo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logo2, "DraARL-PTT");
    lv_obj_set_style_text_color(ui_logo2, lv_color_hex(0x00DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_logo2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title1 = lv_label_create(ui_header2);
    lv_obj_set_width(ui_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title1, "射频");
    lv_obj_set_style_text_font(ui_title1, &ui_font_system20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat1 = lv_img_create(ui_header2);
    lv_img_set_src(ui_wifistat1, &ui_img_wifi_bad_png);
    lv_obj_set_width(ui_wifistat1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifistat1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifistat1, 140);
    lv_obj_set_y(ui_wifistat1, 0);
    lv_obj_set_align(ui_wifistat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifistat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bluestat1 = lv_img_create(ui_header2);
    lv_img_set_src(ui_bluestat1, &ui_img_bluetooth_disabled_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_bluestat1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_bluestat1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_bluestat1, 110);
    lv_obj_set_y(ui_bluestat1, 0);
    lv_obj_set_align(ui_bluestat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bluestat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluestat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hasNewUpdate1 = lv_img_create(ui_header2);
    lv_img_set_src(ui_hasNewUpdate1, &ui_img_browser_updated_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_hasNewUpdate1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_hasNewUpdate1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_hasNewUpdate1, 80);
    lv_obj_set_y(ui_hasNewUpdate1, 0);
    lv_obj_set_align(ui_hasNewUpdate1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hasNewUpdate1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hasNewUpdate1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_RFPAGE_screen_destroy(void)
{
    if(ui_RFPAGE) lv_obj_del(ui_RFPAGE);

    // NULL screen variables
    ui_RFPAGE = NULL;
    ui_BLEP1 = NULL;
    ui_Label10 = NULL;
    ui_BLES1 = NULL;
    ui_BLEN1 = NULL;
    ui_header2 = NULL;
    ui_logo2 = NULL;
    ui_title1 = NULL;
    ui_wifistat1 = NULL;
    ui_bluestat1 = NULL;
    ui_hasNewUpdate1 = NULL;

}
