// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#include "ui.h"

lv_obj_t * ui_RFPAGE = NULL;
lv_obj_t * ui_PWP = NULL;
lv_obj_t * ui_PWL = NULL;
lv_obj_t * ui_PWS = NULL;
lv_obj_t * ui_PWN = NULL;
lv_obj_t * ui_LimitP = NULL;
lv_obj_t * ui_PWL1 = NULL;
lv_obj_t * ui_rfguard = NULL;
lv_obj_t * ui_rfguardsingle = NULL;
lv_obj_t * ui_rfguardwindow = NULL;
lv_obj_t * ui_rfguardmaxtxinwindow = NULL;
lv_obj_t * ui_header2 = NULL;
lv_obj_t * ui_logo2 = NULL;
lv_obj_t * ui_title1 = NULL;
lv_obj_t * ui_wifistat1 = NULL;
lv_obj_t * ui_bluestat1 = NULL;
lv_obj_t * ui_hasNewUpdate1 = NULL;
// event funtions

// build funtions

void ui_RFPAGE_screen_init(void)
{
    ui_RFPAGE = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RFPAGE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWP = lv_obj_create(ui_RFPAGE);
    lv_obj_set_width(ui_PWP, 310);
    lv_obj_set_height(ui_PWP, 40);
    lv_obj_set_x(ui_PWP, 0);
    lv_obj_set_y(ui_PWP, -63);
    lv_obj_set_align(ui_PWP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PWP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWL = lv_label_create(ui_PWP);
    lv_obj_set_width(ui_PWL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWL, -125);
    lv_obj_set_y(ui_PWL, 0);
    lv_obj_set_align(ui_PWL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWL, "功率:");
    lv_obj_set_style_text_font(ui_PWL, &ui_font_system, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWS = lv_switch_create(ui_PWP);
    lv_obj_set_width(ui_PWS, 50);
    lv_obj_set_height(ui_PWS, 25);
    lv_obj_set_x(ui_PWS, 115);
    lv_obj_set_y(ui_PWS, 0);
    lv_obj_set_align(ui_PWS, LV_ALIGN_CENTER);

    ui_PWN = lv_label_create(ui_PWP);
    lv_obj_set_width(ui_PWN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWN, 73);
    lv_obj_set_y(ui_PWN, 0);
    lv_obj_set_align(ui_PWN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWN, "低");
    lv_obj_set_style_text_font(ui_PWN, &ui_font_system, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LimitP = lv_obj_create(ui_RFPAGE);
    lv_obj_set_width(ui_LimitP, 310);
    lv_obj_set_height(ui_LimitP, 150);
    lv_obj_set_x(ui_LimitP, 0);
    lv_obj_set_y(ui_LimitP, 40);
    lv_obj_set_align(ui_LimitP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LimitP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWL1 = lv_label_create(ui_LimitP);
    lv_obj_set_width(ui_PWL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWL1, -92);
    lv_obj_set_y(ui_PWL1, 2);
    lv_obj_set_align(ui_PWL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWL1, "长发保护:\n\n单次发射上限:\n\n窗口大小:\n\n窗口发射上限:");
    lv_obj_set_style_text_font(ui_PWL1, &ui_font_system, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rfguard = lv_switch_create(ui_LimitP);
    lv_obj_set_width(ui_rfguard, 50);
    lv_obj_set_height(ui_rfguard, 25);
    lv_obj_set_x(ui_rfguard, 115);
    lv_obj_set_y(ui_rfguard, -53);
    lv_obj_set_align(ui_rfguard, LV_ALIGN_CENTER);

    ui_rfguardsingle = lv_label_create(ui_LimitP);
    lv_obj_set_width(ui_rfguardsingle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rfguardsingle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rfguardsingle, 110);
    lv_obj_set_y(ui_rfguardsingle, -15);
    lv_obj_set_align(ui_rfguardsingle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rfguardsingle, "30s");

    ui_rfguardwindow = lv_label_create(ui_LimitP);
    lv_obj_set_width(ui_rfguardwindow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rfguardwindow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rfguardwindow, 110);
    lv_obj_set_y(ui_rfguardwindow, 20);
    lv_obj_set_align(ui_rfguardwindow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rfguardwindow, "60s");

    ui_rfguardmaxtxinwindow = lv_label_create(ui_LimitP);
    lv_obj_set_width(ui_rfguardmaxtxinwindow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rfguardmaxtxinwindow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rfguardmaxtxinwindow, 110);
    lv_obj_set_y(ui_rfguardmaxtxinwindow, 55);
    lv_obj_set_align(ui_rfguardmaxtxinwindow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rfguardmaxtxinwindow, "40s");

    ui_header2 = lv_obj_create(ui_RFPAGE);
    lv_obj_remove_style_all(ui_header2);
    lv_obj_set_width(ui_header2, 320);
    lv_obj_set_height(ui_header2, 30);
    lv_obj_set_x(ui_header2, 0);
    lv_obj_set_y(ui_header2, -105);
    lv_obj_set_align(ui_header2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_header2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_header2, lv_color_hex(0x22262D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo2 = lv_label_create(ui_header2);
    lv_obj_set_width(ui_logo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo2, -110);
    lv_obj_set_y(ui_logo2, 0);
    lv_obj_set_align(ui_logo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logo2, "DraARL-PTT");
    lv_obj_set_style_text_color(ui_logo2, lv_color_hex(0x00DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_logo2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title1 = lv_label_create(ui_header2);
    lv_obj_set_width(ui_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title1, "射频");
    lv_obj_set_style_text_font(ui_title1, &ui_font_system20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat1 = lv_img_create(ui_header2);
    lv_img_set_src(ui_wifistat1, &ui_img_wifi_bad_png);
    lv_obj_set_width(ui_wifistat1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifistat1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifistat1, 140);
    lv_obj_set_y(ui_wifistat1, 0);
    lv_obj_set_align(ui_wifistat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifistat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bluestat1 = lv_img_create(ui_header2);
    lv_img_set_src(ui_bluestat1, &ui_img_bluetooth_disabled_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_bluestat1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_bluestat1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_bluestat1, 110);
    lv_obj_set_y(ui_bluestat1, 0);
    lv_obj_set_align(ui_bluestat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bluestat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluestat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hasNewUpdate1 = lv_img_create(ui_header2);
    lv_img_set_src(ui_hasNewUpdate1, &ui_img_browser_updated_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_hasNewUpdate1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_hasNewUpdate1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_hasNewUpdate1, 80);
    lv_obj_set_y(ui_hasNewUpdate1, 0);
    lv_obj_set_align(ui_hasNewUpdate1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hasNewUpdate1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hasNewUpdate1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_RFPAGE_screen_destroy(void)
{
    if(ui_RFPAGE) lv_obj_del(ui_RFPAGE);

    // NULL screen variables
    ui_RFPAGE = NULL;
    ui_PWP = NULL;
    ui_PWL = NULL;
    ui_PWS = NULL;
    ui_PWN = NULL;
    ui_LimitP = NULL;
    ui_PWL1 = NULL;
    ui_rfguard = NULL;
    ui_rfguardsingle = NULL;
    ui_rfguardwindow = NULL;
    ui_rfguardmaxtxinwindow = NULL;
    ui_header2 = NULL;
    ui_logo2 = NULL;
    ui_title1 = NULL;
    ui_wifistat1 = NULL;
    ui_bluestat1 = NULL;
    ui_hasNewUpdate1 = NULL;

}
