// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32

#include "ui.h"

lv_obj_t * ui_StartUP = NULL;
lv_obj_t * ui_Arc1 = NULL;
// event funtions

// build funtions

void ui_StartUP_screen_init(void)
{
    ui_StartUP = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_StartUP);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

}

void ui_StartUP_screen_destroy(void)
{
    if(ui_StartUP) lv_obj_del(ui_StartUP);

    // NULL screen variables
    ui_StartUP = NULL;
    ui_Arc1 = NULL;

}
