// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#include "ui.h"

lv_obj_t * ui_startUP = NULL;
// event funtions

// build funtions

void ui_startUP_screen_init(void)
{
    ui_startUP = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_startUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_startUP_screen_destroy(void)
{
    if(ui_startUP) lv_obj_del(ui_startUP);

    // NULL screen variables
    ui_startUP = NULL;

}
