// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#include "ui.h"

lv_obj_t * ui_SettingPAGE = NULL;
// event funtions

// build funtions

void ui_SettingPAGE_screen_init(void)
{
    ui_SettingPAGE = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingPAGE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_SettingPAGE_screen_destroy(void)
{
    if(ui_SettingPAGE) lv_obj_del(ui_SettingPAGE);

    // NULL screen variables
    ui_SettingPAGE = NULL;

}
