// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#ifndef UI_SETTINGPAGE_H
#define UI_SETTINGPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingPAGE
extern void ui_SettingPAGE_screen_init(void);
extern void ui_SettingPAGE_screen_destroy(void);
extern lv_obj_t * ui_SettingPAGE;
extern lv_obj_t * ui_lightP;
extern lv_obj_t * ui_LightS;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_autoupdate;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_updateBT;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BLEP;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_BLES;
extern lv_obj_t * ui_BLEN;
extern lv_obj_t * ui_autostart;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_StartS;
extern lv_obj_t * ui_RFP;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_InfoP;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_header3;
extern lv_obj_t * ui_logo3;
extern lv_obj_t * ui_title2;
extern lv_obj_t * ui_wifistat2;
extern lv_obj_t * ui_bluestat2;
extern lv_obj_t * ui_hasNewUpdate2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

