// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32

#ifndef UI_STARTUP_H
#define UI_STARTUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartUP
extern void ui_StartUP_screen_init(void);
extern void ui_StartUP_screen_destroy(void);
extern lv_obj_t * ui_StartUP;
extern lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

