// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DraARL-ESP32-v1

#ifndef UI_SETTINGPAGE_H
#define UI_SETTINGPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingPAGE
extern void ui_SettingPAGE_screen_init(void);
extern void ui_SettingPAGE_screen_destroy(void);
extern lv_obj_t * ui_SettingPAGE;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

